CREATE TABLE IF NOT EXISTS postachannya_raw (
    order_id VARCHAR(50) PRIMARY KEY,
    order_name VARCHAR(255),
    order_date TIMESTAMP,
    client_id VARCHAR(50),
    manager_id VARCHAR(50),
    manager VARCHAR(255),
    author_id VARCHAR(50),
    author VARCHAR(255),
    process_id VARCHAR(50),
    process_name VARCHAR(255),
    order_status_id VARCHAR(50),
    order_status VARCHAR(255),
    client_phone VARCHAR(100),
    client_email VARCHAR(255),
    client_name VARCHAR(255),
    order_sum NUMERIC,
    delivery_note TEXT,
    legal_entity_id VARCHAR(50),
    incoming VARCHAR(255),
    external_id VARCHAR(255),
    order_father_id VARCHAR(50),
    order_Oplacheno VARCHAR(100),
    order_Nashizobovyazannya VARCHAR(100),
    order_Zobovyazannyaklinta VARCHAR(100),
    legal_entity_name VARCHAR(255),
    order_Sumaprotsesupostach VARCHAR(100),
    order_delivery_date TIMESTAMP,
    order_father_name VARCHAR(255),
    
    -- Вкладені товари
    products JSONB
);