CREATE TABLE IF NOT EXISTS zakupivlya_raw (
    order_id VARCHAR(50) PRIMARY KEY,
    order_name VARCHAR(255),
    order_date TIMESTAMP,
    client_id VARCHAR(50),
    manager_id VARCHAR(50),
    manager VARCHAR(255),
    author_id VARCHAR(50),
    author VARCHAR(255),
    process_id VARCHAR(50),
    process_name VARCHAR(255),
    order_status_id VARCHAR(50),
    order_status VARCHAR(255),
    client_phone VARCHAR(100),
    client_email VARCHAR(255),
    client_name VARCHAR(255),
    order_sum NUMERIC,
    delivery_note TEXT,
    legal_entity_id VARCHAR(50),
    incoming VARCHAR(255),
    external_id VARCHAR(255),
    legal_entity_name VARCHAR(255),
    order_Deadline_date TIMESTAMP,
    order_completion_date TIMESTAMP,
    zayavkanazakupivlyudataperehodunaetappriinyato TIMESTAMP,
    zayavkanazakupivlyudataperehodunavobrobtsi TIMESTAMP,
    zayavkanazakupivlyudataperehodunaetapzamovleno TIMESTAMP,
    zayavkanazakupivlyudataperehodunaetapvikonano TIMESTAMP,
    zayavkanazakupivlyudataperehodunaetapvdorozi TIMESTAMP,
    order_rating_score VARCHAR(50),
    
    -- Вкладені товари
    products JSONB
);