CREATE TABLE IF NOT EXISTS clients_raw (
    order_id VARCHAR(50) PRIMARY KEY,
    order_name VARCHAR(255),
    order_date TIMESTAMP,
    client_id VARCHAR(50),
    manager_id VARCHAR(50),
    manager VARCHAR(255),
    author_id VARCHAR(50),
    author VARCHAR(255),
    process_id VARCHAR(50),
    process_name VARCHAR(255),
    order_status_id VARCHAR(50),
    order_status VARCHAR(255),
    client_phone VARCHAR(100),
    client_email VARCHAR(255),
    client_name VARCHAR(255),
    order_sum NUMERIC,
    delivery_note TEXT,
    legal_entity_id VARCHAR(50),
    order_source_id VARCHAR(50),
    order_source VARCHAR(255),
    external_id VARCHAR(255),
    products JSONB,
    order_final_date TIMESTAMP,
    order_postpaid_days VARCHAR(50),
    order_Potribnaperedplata VARCHAR(50),
    order_Grupaklinta VARCHAR(255),
    legal_entity_name VARCHAR(255),
    order_Vidsotokperedplati VARCHAR(50),
    order_Ochikuvaniiterminperedplatidni VARCHAR(50),
    order_paid_sum NUMERIC
);